application: webkit-commit-queue
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.py
