import Options

def set_options(opt):
    opt.tool_options("compiler_cxx")

def configure(conf):
    conf.check_tool("compiler_cxx")
    conf.check_tool("node_addon")
    conf.env.append_value('LINKFLAGS', ['-l:ail.so', '-L/home/kja/Artemis/ailproxy/testmodule/ailreader/src/',])

def build(bld):
    obj = bld.new_task_gen("cxx", "shlib", "node_addon")
    obj.target = "AIL"
    obj.source = ["AIL.cc","reader.cc"]