#!/usr/bin/env python

def set_options(ctx):
    ctx.tool_options('compiler_cxx')

def configure(ctx):
    ctx.check_tool('compiler_cxx')
    ctx.check_tool('node_addon')
    ctx.env.append_value('LINKFLAGS', ['-l:ail.so', '-L/home/kja/Artemis/ailreader/ail-module/', '-I/home/kja/Artemis/ailreader/ail-module/ailreader/src/'])

def build(ctx):
    t = ctx.new_task_gen('cxx', 'shlib', 'node_addon')
    t.source = ['ailreader.cpp']
    t.target = 'ailreader'
