#define TOKEN_AIL_START                 1
#define TOKEN_DOMAIN                    2
#define TOKEN_METHOD                    3
#define TOKEN_ROUND_BRACKET_OPEN        4
#define TOKEN_ROUND_BRACKET_CLOSE       5
#define TOKEN_COLON                     6
#define TOKEN_STRING                    7
#define TOKEN_SLASH                     8
#define TOKEN_COMMA                     9
#define TOKEN_VOID                     10
#define TOKEN_AT                       11
#define TOKEN_PIPE                     12
